package com.bng.core.entity;
// Generated 14 Nov, 2013 12:00:29 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CircleMapper generated by hbm2java
 */
@Entity
@Table(name="CIRCLE_MAPPER"
    ,catalog="IVR_DATA"
    , uniqueConstraints = @UniqueConstraint(columnNames={"SERIES", "CIRCLE"}) 
)
public class CircleMapper  implements java.io.Serializable {


     private Integer id;
     private String circle;
     private String circleKey;
     private String country;
     private String countryKey;
     private String defLang;
     private String operator;
     private int series;
     private String timeZone;

    public CircleMapper() {
    }

	
    public CircleMapper(int series) {
        this.series = series;
    }
    public CircleMapper(String circle, String circleKey, String country, String countryKey, String defLang, String operator, int series, String timeZone) {
       this.circle = circle;
       this.circleKey = circleKey;
       this.country = country;
       this.countryKey = countryKey;
       this.defLang = defLang;
       this.operator = operator;
       this.series = series;
       this.timeZone = timeZone;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="CIRCLE", length=15)
    public String getCircle() {
        return this.circle;
    }
    
    public void setCircle(String circle) {
        this.circle = circle;
    }
    
    @Column(name="CIRCLE_KEY", length=3)
    public String getCircleKey() {
        return this.circleKey;
    }
    
    public void setCircleKey(String circleKey) {
        this.circleKey = circleKey;
    }
    
    @Column(name="COUNTRY", length=20)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    
    @Column(name="COUNTRY_KEY", length=3)
    public String getCountryKey() {
        return this.countryKey;
    }
    
    public void setCountryKey(String countryKey) {
        this.countryKey = countryKey;
    }
    
    @Column(name="DEF_LANG", length=3)
    public String getDefLang() {
        return this.defLang;
    }
    
    public void setDefLang(String defLang) {
        this.defLang = defLang;
    }
    
    @Column(name="OPERATOR", length=15)
    public String getOperator() {
        return this.operator;
    }
    
    public void setOperator(String operator) {
        this.operator = operator;
    }
    
    @Column(name="SERIES", nullable=false)
    public int getSeries() {
        return this.series;
    }
    
    public void setSeries(int series) {
        this.series = series;
    }
    
    @Column(name="TIME_ZONE", length=10)
    public String getTimeZone() {
        return this.timeZone;
    }
    
    public void setTimeZone(String timeZone) {
        this.timeZone = timeZone;
    }




}


