package com.bng.core.entity;
// Generated 14 Nov, 2013 12:00:29 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IvrBlacklist generated by hbm2java
 */
@Entity
@Table(name="IVR_BLACKLIST"
    ,catalog="IVR_DATA"
)
public class IvrBlacklist  implements java.io.Serializable {


     private int id;
     private Date date;
     private Integer isSeries;
     private String msisdn;

    public IvrBlacklist() {
    }

	
    public IvrBlacklist(int id) {
        this.id = id;
    }
    public IvrBlacklist(int id, Date date, Integer isSeries, String msisdn) {
       this.id = id;
       this.date = date;
       this.isSeries = isSeries;
       this.msisdn = msisdn;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE", length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    
    @Column(name="IS_SERIES")
    public Integer getIsSeries() {
        return this.isSeries;
    }
    
    public void setIsSeries(Integer isSeries) {
        this.isSeries = isSeries;
    }
    
    @Column(name="MSISDN", length=10)
    public String getMsisdn() {
        return this.msisdn;
    }
    
    public void setMsisdn(String msisdn) {
        this.msisdn = msisdn;
    }




}


